apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: demo-app
